### PR TITLE
Widgets - Publish

### PR DESCRIPTION
**Pull request by pannga**

### CODE REVIEW

**Review by darekg11 — CHANGES_REQUESTED** [review]
Request changes:
- logic errors
- duplicated code

**Comment by pannga** [comment]
@darekg11 I've moved a lot of stuff to other files & created and reused `createInput` function & got rid of this horrible clsx mess.

**Review by darekg11 — CHANGES_REQUESTED** [review]
Some minor changes required.

**Comment by pannga** [comment]
Updated component :)

**Review by darekg11 — APPROVED** [review]
Thank you

**Pull request merged**
